version: 0.1
os: linux
files:
  - source: /
    destination: /var/www/html/news
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
